require: rubocop-rails # rails cops extracted to separate gem in last version

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'db/migrate/**'
    - 'config/**/*'
    - 'config/environnements/**'
    - 'bin/**/*'
    - 'tmp/*'
    - 'Guardfile'
    - 'node_modules/**/*' #webpacker & rails 5.1

Metrics/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma